### ISSUE TITLE
Setting up Looper and pipelines

### ISSUE THREAD

**Issue by weizhiting** [epigen/crop-seq#1]
Hi!
when i run this command   'make  makeref' command, i got an error. Indeed,it caused by this 
prj = Project(os.path.join("metadata", "config.yaml")),Could you help me! Moreover,in the config.yaml,what does the pipelines_dir refer to?Thanks!

**Comment by afrendeiro** [comment]
Hello!

This repository used the project management system [Looper](https://github.com/epigen/looper) to handle the project, but also to process the raw data. You can read [here](http://looper.readthedocs.io/en/latest/?badge=latest) more on it and how to set it up.

I don't know what error you got, but for the project management part you have to have looper installed: e.g. `pip install --user https://github.com/epigen/looper/zipball/master`. To make sure all requirements are satisfied you can run `make requirements` which will try to get all requirements from [requirements.txt](https://github.com/epigen/crop-seq/blob/master/requirements.txt).

If you want to process the raw data you have to have additionally a looper-compatible pipeline repository [like this one](https://github.com/epigen/open_pipelines) where you'll find the Drop-seq pipeline I used to process the data (this in addition has its own requirements), but since this is perhaps a bit complex I recommend you just get the processed data from GEO if your intention is to play with it.

**Comment by weizhiting** [comment]
Hi!
Thanks! I will try what you said!

**Comment by afrendeiro** [comment]
Please feel free to reopen the issue if more problems arise.
